from __future__ import annotations

from typing import Any, AsyncIterator, Protocol, runtime_checkable


@runtime_checkable
class LLMAdapter(Protocol):
    async def complete(self, request: dict[str, Any]) -> dict[str, Any]: ...

    async def stream(self, request: dict[str, Any]) -> AsyncIterator[str]: ...

    def supports_vision(self) -> bool: ...

    def supports_tool_calls(self) -> bool: ...

    def token_budget(self) -> int: ...
