"""agents/calculator_application_for_agent.py

Agent generated by Freya for: calculator_application_for
"""
from __future__ import annotations

import re
import time

from freya.agents.base import AgentContext, AgentResult, AgentStatus, OperationalAgent
from tools.calculator_application_for_tools import add, subtract, multiply, divide


class CalculatorApplicationForAgent(OperationalAgent):
    @property
    def name(self) -> str:
        return "CalculatorApplicationForAgent"

    @property
    def domain(self) -> str:
        return "calculator_application_for"

    _OP_PATTERNS = [
        (r"\b(?:add|plus)\b|\+",                "add"),
        (r"\b(?:subtract|minus)\b",             "subtract"),
        (r"\b(?:multiply|times|x)\b|\*",        "multiply"),
        (r"\b(?:divide|divided\s+by|over)\b|/", "divide"),
    ]

    def _parse_prompt(self, prompt: str) -> dict:
        op_matched = False
        op = "add"
        for pattern, name in self._OP_PATTERNS:
            if re.search(pattern, prompt, re.IGNORECASE):
                op = name
                op_matched = True
                break
        nums = re.findall(r"-?\d+(?:\.\d+)?", prompt)
        return {
            "operation": op,
            "a": float(nums[0]) if len(nums) > 0 else 0.0,
            "b": float(nums[1]) if len(nums) > 1 else 0.0,
            "_op_matched": op_matched,
            "_nums_found": len(nums),
        }

    async def execute(self, context: AgentContext) -> AgentResult:
        t0 = time.monotonic()
        parsed: dict = {}
        if "operation" not in context.state:
            parsed = self._parse_prompt(context.objective)
            context.state.update(parsed)

        nums_found = parsed.get("_nums_found", 1)
        if nums_found == 0:
            elapsed = (time.monotonic() - t0) * 1000
            return self._result(
                status=AgentStatus.FAILED,
                errors=[f"No numeric operands found in: '{context.objective}'"],
                narration="Prompt is outside this agent's capabilities (expected a numeric expression).",
                elapsed_ms=elapsed,
            )

        warnings = []
        if not parsed.get("_op_matched", True):
            warnings.append(f"No operation keyword recognised — defaulted to 'add'.")
        if nums_found == 1:
            warnings.append("Only one operand found — second operand defaulted to 0.")

        operation = context.state.get("operation", "add")
        ops = {
            "add": add,
            "subtract": subtract,
            "multiply": multiply,
            "divide": divide,
        }
        fn = ops.get(operation, add)
        a = context.state.get("a", 0.0)
        b = context.state.get("b", 0.0)
        try:
            result = fn(a, b)
        except ZeroDivisionError:
            elapsed = (time.monotonic() - t0) * 1000
            return self._result(
                status=AgentStatus.FAILED,
                errors=["Division by zero."],
                narration=f"{operation}({a}, {b}) failed: division by zero.",
                elapsed_ms=elapsed,
            )
        elapsed = (time.monotonic() - t0) * 1000
        return self._result(
            status=AgentStatus.SUCCEEDED,
            output={"result": result, "operation": operation},
            narration=f"{operation}({a}, {b}) = {result}",
            warnings=warnings,
            elapsed_ms=elapsed,
        )
